### ISSUE TITLE
Runtime 

### ISSUE THREAD

**Issue by chenlingantelope** [MarioniLab/MNN2017#11]
The following dataset contains ~76K cells and according to the paper should take ~20mins but I ran it for >24h and obtained no output. Both of them are from the 10x website 
https://support.10xgenomics.com/single-cell-gene-expression/datasets/2.1.0/pbmc8k
https://support.10xgenomics.com/single-cell-gene-expression/datasets/1.1.0/fresh_68k_pbmc_donor_a

> data1 = 'data/pairwise/pbmc8k.mtx'
> data2 = 'data/pairwise/pbmc68k.mtx'
> data <- lapply(c(data1,data2),function(fname){
> 	X = readMM(fname)
> 	return(t(X))
> })
> library(scran)
> ibrary('gmodels')
> data1= as.matrix(data[[1]])
> data2= as.matrix(data[[2]])
> start = proc.time()
> mnn_correct <- mnnCorrect(data1, data2) # corrected values
> end = proc.time()

**Comment by LTLA** [comment]
If you read the `README`, it'll direct you to https://github.com/MarioniLab/FurtherMNN2018.

But to answer your immediate question, I would suggest some feature selection before throwing it into `mnnCorrect`. It's not like `removeBatchEffect`, it doesn't work on a gene-by-gene basis.
