### ISSUE TITLE
Missing Files/ incorrect instructions to recreate figures

### ISSUE THREAD

**Issue by ejarmand** [MarioniLab/MNN2017#12]
In README.md one is directed to run "FourPlots_sim.R", "FourPlots_easysim.R" or "FourPlots_haem.R" to recreate the figures from Haghverdi et al.

Unfortunately none of these files exist in the directories they are said to exist in or at all.

**Comment by LTLA** [comment]
`plotCorrections.R` should be the equivalent script; it was an attempt to standardize the scripts across repositories that I eventually just gave up on. Unless you're specifically interested in the figures from the paper, I would suggest you check out the _FurtherMNN2018_ repository instead, which is actually kept functional and standardized. I suspect that this particular repository will be archived soon.

**Comment by LTLA** [comment]
Fixed the `README` as much as I could. Note that [the workflow](http://bioconductor.org/packages/devel/workflows/vignettes/simpleSingleCell/inst/doc/work-5-mnn.html) provides a more pedagogical approach than scanning through the scripts in this repository, which are quite cryptic even for me.
