### ISSUE TITLE
cell label for MAP.csv

### ISSUE THREAD

**Issue by jhu99** [MarioniLab/MNN2017#15]
There are 2730 cells in the annotation file MAP.csv. However, only 2729 was used in the script. Probably, there should be a header line in the file.

**Comment by LTLA** [comment]
Yes, you're right. Fortunately, the `sceA <- sceA[,metainds]` line means that it's not a catastrophic annotation mismatch. Nonetheless, it's fixed in https://github.com/MarinoniLab/FurtherMNN2018 - please see the `README` in this repository.
