### ISSUE TITLE
Where does MAP.csv in Haematopoeisis come from?

### ISSUE THREAD

**Issue by LTLA** [MarioniLab/MNN2017#5]
We should provide instructions on how to obtain this, if it is publicly available somewhere. If we got it by personal communication, then this should be mentioned in the comments.

**Comment by LTLA** [comment]
It's in the `Haematopoiesis` folder.

**Comment by podorskaja** [comment]
I understand that the actual `MAP.csv` is in the `Haematopoiesis` folder and is based on the paper by Paul et al. What I am wondering is how exactly did you get the data inside this file?

**Comment by LTLA** [comment]
I believe it was obtained from the authors directly. @LalehHaghverdi?

**Comment by LalehHaghverdi** [comment]
True, how to get the cell type labels (FACs index sorting) is described in Fig. 1 of Paul et al. (2015) paper. We asked the authors for the cell type labels.
