### ISSUE TITLE
Is it possible that MNN method can remove "batch" effect between 3' UMI data and  full-length read-based data ?

### ISSUE THREAD

**Issue by ahy1221** [MarioniLab/MNN2017#8]
Such a feature would be quite useful for combing 10X/dropseq data with smartseq2  data.
Since the MNN method implicitly performs cell alignment using MNN pairs between different batches, I think the challenge would be how to normalize the data for MNN pairs searching.

**Comment by LTLA** [comment]
Yes, I think we did this in the paper, with the 68K PBMCs and another T cell dataset.
